name: flixpedia
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^5.1.0
  http: ^1.1.0
  carousel_slider: ^4.2.1
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.14.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.5
  flutter_staggered_grid_view: ^0.4.1 # Use the latest version available
  cached_network_image: ^3.2.0 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/